services:
  postgres:
    container_name: postgres-db
    image: postgres:14.19-trixie
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_USER:-T4k8_40By3Â£3MGj}
      - POSTGRES_DB=${POSTGRES_USER:-test_db}
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgres"

volumes:
  pg_data: {}